// First-time bootstrap for local dev. Idempotent — safe to re-run.
//
// 1. Initialise embedded Postgres data dir (if missing)
// 2. Boot it, create `new_terra` database (if missing)
// 3. Write repo-root .env and client/.env (if missing) with sane dev values
//    + a freshly-generated JWT_SECRET
// 4. Run `prisma migrate deploy` against the embedded DB
// 5. Seed demo data (optional — pass --no-seed to skip)
// 6. Stop PG and exit
//
// After this, `npm run dev` brings everything up.

import EmbeddedPostgres from 'embedded-postgres';
import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..', '..');
const serverDir = path.resolve(__dirname, '..');
const clientDir = path.resolve(repoRoot, 'client');
const dataDir = path.resolve(serverDir, '.pgdata');

const port = Number(process.env.LOCAL_PG_PORT ?? 5432);
const dbName = 'new_terra';
const dbUser = 'postgres';
const dbPass = 'postgres';
const databaseUrl = `postgresql://${dbUser}:${dbPass}@localhost:${port}/${dbName}?schema=public`;

const skipSeed = process.argv.includes('--no-seed');

function log(msg: string) {
  console.log(`[setup] ${msg}`);
}

function writeIfMissing(file: string, contents: string): boolean {
  if (fs.existsSync(file)) {
    log(`skip (exists): ${path.relative(repoRoot, file)}`);
    return false;
  }
  fs.writeFileSync(file, contents);
  log(`wrote: ${path.relative(repoRoot, file)}`);
  return true;
}

function generateJwtSecret(): string {
  return crypto.randomBytes(48).toString('hex');
}

function rootEnvContents(): string {
  return [
    '# Local dev — generated by `npm run db:setup`. Safe to edit.',
    '# This file is gitignored. The VM has its own .env.',
    '',
    `DATABASE_URL=${databaseUrl}`,
    'PORT=4000',
    'NODE_ENV=development',
    '',
    `JWT_SECRET=${generateJwtSecret()}`,
    'JWT_EXPIRES_IN=7d',
    '',
    'APP_URL=http://localhost:5173',
    '',
    '# Bootstrap admin (db:seed creates this if no admin exists)',
    'SEED_ADMIN_EMAIL=admin@newterraconstruction.com',
    'SEED_ADMIN_PASSWORD=changeMe!2026',
    'SEED_ADMIN_NAME=Site Admin',
    '',
    '# SMTP unset → invite links logged to server console (fine for dev)',
    'SMTP_HOST=',
    'INQUIRY_TO=sales@newterraconstruction.com',
    '',
  ].join('\n');
}

function clientEnvContents(): string {
  return ['VITE_API_URL=http://localhost:4000', ''].join('\n');
}

const pg = new EmbeddedPostgres({
  databaseDir: dataDir,
  user: dbUser,
  password: dbPass,
  port,
  persistent: true,
  // UTF-8 + C locale; default Windows locale (WIN1252) can't store
  // emojis or any 4-byte UTF-8 character.
  initdbFlags: ['--encoding=UTF8', '--locale=C'],
});

async function main() {
  // 1. Initialise data dir if missing
  if (!fs.existsSync(path.join(dataDir, 'PG_VERSION'))) {
    log(`initialising postgres data dir at ${dataDir}…`);
    await pg.initialise();
  } else {
    log('postgres data dir exists — skipping initialise');
  }

  // 2. Start + create DB
  log(`starting postgres on localhost:${port}…`);
  await pg.start();

  try {
    await pg.createDatabase(dbName);
    log(`created database "${dbName}"`);
  } catch (err: any) {
    const msg = String(err?.message ?? err);
    if (msg.includes('already exists')) {
      log(`database "${dbName}" already exists — skipping create`);
    } else {
      throw err;
    }
  }

  // 3. Env files
  writeIfMissing(path.join(repoRoot, '.env'), rootEnvContents());
  writeIfMissing(path.join(clientDir, '.env'), clientEnvContents());

  // 4. Generate Prisma client + run migrations (use deploy — applies existing
  //    migrations without prompts)
  log('generating prisma client…');
  execSync('npx prisma generate', {
    cwd: serverDir,
    stdio: 'inherit',
    env: { ...process.env, DATABASE_URL: databaseUrl },
  });

  log('running prisma migrate deploy…');
  execSync('npx prisma migrate deploy', {
    cwd: serverDir,
    stdio: 'inherit',
    env: { ...process.env, DATABASE_URL: databaseUrl },
  });

  // 5. Seed demo data
  if (!skipSeed) {
    log('seeding demo data (pass --no-seed to skip)…');
    execSync('npm run db:seed:demo', {
      cwd: serverDir,
      stdio: 'inherit',
      env: { ...process.env, DATABASE_URL: databaseUrl },
    });
  } else {
    log('skipping seed (--no-seed)');
  }

  // 6. Stop
  await pg.stop();
  log('done. start dev with: npm run dev');
}

main().catch(async (err) => {
  console.error('[setup] failed:', err);
  try {
    await pg.stop();
  } catch {}
  process.exit(1);
});
